title: Thermodynamics and Combustion Engineering Laboratory

email:  varuns@iitm.ac.in

description: >
  This lab's goal ... 

timezone: "Asia/Kolkata"
  
baseurl: "" 
url    : "https://tdceiitm.github.io/"

include: ['_pages']

collections:
  news:
  events:
  project:
  research:
  members:
     permalink: /:collection/:path/
     output: true

future: true

authors:
  krithika:
    name: Krithika Narayanaswamy
  sivaram:
    name: Sivaram Ambikasaran
